version: 2
sources:
  - name: raw
    database: ECOMMERCE
    schema: RAW
    tables:
      - name: customers
      - name: products
      - name: orders
      - name: order_items
      - name: product_reviews
