models:

  - name: stg_customers
    columns:
      - name: customer_id
        tests: [not_null, unique]

  - name: stg_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id

  - name: stg_products
    columns:
      - name: product_id
        tests: [not_null, unique]

  - name: stg_order_items
    columns:
      - name: order_item_id
        tests: [not_null, unique]
      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id
      - name: order_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_id

  - name: stg_product_reviews
    columns:
      - name: review_id
        tests: [not_null, unique]

  - name: dim_customers
    columns:
      - name: customer_id
        tests: [not_null, unique]

  - name: dim_products
    columns:
      - name: product_id
        tests: [not_null, unique]

  - name: fact_orders
    columns:
      - name: order_id
        tests: [not_null, unique]

  - name: fact_order_items
    columns:
      - name: order_item_id
        tests: [not_null, unique]
