ecommerce_snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SF_ACCOUNT') }}"
      user: "{{ env_var('SF_USER') }}"
      password: "{{ env_var('SF_PASSWORD') }}"
      warehouse: "{{ env_var('SF_WAREHOUSE', 'ETL_XS') }}"
      database: "{{ env_var('SF_DATABASE', 'ECOMMERCE') }}"
      schema: ""
      threads: 4
